### PR TITLE
add locale: RU, UK add multi-search (options.html)

### PR DESCRIPTION
**Pull request by perdolka**

### CODE REVIEW

**Comment by perdolka** [comment]
Translator:
Henaro aka Ironwool https://github.com/perdolka

**Comment by perdolka** [comment]
Also, added favicon as you see. ;)

**Comment by odebroqueville** [comment]
@perdolka Very nice work. Thanks so much. If I'm not mistaken, I'll just have to change the country code for Ukraine to UA: http://www.nationsonline.org/oneworld/country_code_list.htm

**Comment by perdolka** [comment]
No, this is not a mistake.
UA - this is country code.
uk - locale code
https://msdn.microsoft.com/ru-ru/library/ee825488(v=cs.20).aspx

**Comment by perdolka** [comment]
@Userroman
Ok, thank you.
I don't know which to choose. ;)
I have also found out that in the Ukrainian localization it's called "Скорочення" (Сокращение).
What about my proposal "поисковики"? What do you think?

**Pull request merged**
