### PR TITLE
Update messages.json RU

### PR DESCRIPTION
**Pull request by perdolka**
Thanks to @Userroman

### CODE REVIEW

**Comment by perdolka** [comment]
Do I need to translate '**multi-search**' of the following strings ? :
11
135
175
195
As I see, you left this part empty in line 11.
And on the options page it's 'multi-search' (in English), on this space.

**Comment by Userroman** [comment]
This translation is good, you need to update the add-on version as soon as possible.

**Comment by Smile4ever** [comment]
I think it's best not to translate multi-search and use it as a feature name. What do you think @odebroqueville?

**Comment by Smile4ever** [comment]
@perdolka Please use a better commit message next time by including the locale (language) you translated / updated. Thanks :+1:

**Comment by perdolka** [comment]
> better commit message next time

Ok, sorry )

**Pull request merged**
